// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: customer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeGrpcServiceClient is the client API for SeGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeGrpcServiceClient interface {
	GetAllCustomers(ctx context.Context, in *GetAllCustomersReq, opts ...grpc.CallOption) (*Customers, error)
}

type seGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeGrpcServiceClient(cc grpc.ClientConnInterface) SeGrpcServiceClient {
	return &seGrpcServiceClient{cc}
}

func (c *seGrpcServiceClient) GetAllCustomers(ctx context.Context, in *GetAllCustomersReq, opts ...grpc.CallOption) (*Customers, error) {
	out := new(Customers)
	err := c.cc.Invoke(ctx, "/customer.SeGrpcService/GetAllCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeGrpcServiceServer is the server API for SeGrpcService service.
// All implementations must embed UnimplementedSeGrpcServiceServer
// for forward compatibility
type SeGrpcServiceServer interface {
	GetAllCustomers(context.Context, *GetAllCustomersReq) (*Customers, error)
	mustEmbedUnimplementedSeGrpcServiceServer()
}

// UnimplementedSeGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeGrpcServiceServer struct {
}

func (UnimplementedSeGrpcServiceServer) GetAllCustomers(context.Context, *GetAllCustomersReq) (*Customers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCustomers not implemented")
}
func (UnimplementedSeGrpcServiceServer) mustEmbedUnimplementedSeGrpcServiceServer() {}

// UnsafeSeGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeGrpcServiceServer will
// result in compilation errors.
type UnsafeSeGrpcServiceServer interface {
	mustEmbedUnimplementedSeGrpcServiceServer()
}

func RegisterSeGrpcServiceServer(s grpc.ServiceRegistrar, srv SeGrpcServiceServer) {
	s.RegisterService(&SeGrpcService_ServiceDesc, srv)
}

func _SeGrpcService_GetAllCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCustomersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeGrpcServiceServer).GetAllCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.SeGrpcService/GetAllCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeGrpcServiceServer).GetAllCustomers(ctx, req.(*GetAllCustomersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SeGrpcService_ServiceDesc is the grpc.ServiceDesc for SeGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.SeGrpcService",
	HandlerType: (*SeGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllCustomers",
			Handler:    _SeGrpcService_GetAllCustomers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
