// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: customer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeGrpcServiceClient is the client API for SeGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeGrpcServiceClient interface {
	GetCustomers(ctx context.Context, in *GetCustomersReq, opts ...grpc.CallOption) (*Customers, error)
	GetCustomerById(ctx context.Context, in *GetCustomersReq, opts ...grpc.CallOption) (*Customer, error)
	CreateCustomer(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
}

type seGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeGrpcServiceClient(cc grpc.ClientConnInterface) SeGrpcServiceClient {
	return &seGrpcServiceClient{cc}
}

func (c *seGrpcServiceClient) GetCustomers(ctx context.Context, in *GetCustomersReq, opts ...grpc.CallOption) (*Customers, error) {
	out := new(Customers)
	err := c.cc.Invoke(ctx, "/customer.SeGrpcService/GetCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seGrpcServiceClient) GetCustomerById(ctx context.Context, in *GetCustomersReq, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/customer.SeGrpcService/GetCustomerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seGrpcServiceClient) CreateCustomer(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, "/customer.SeGrpcService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seGrpcServiceClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, "/customer.SeGrpcService/UpdateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeGrpcServiceServer is the server API for SeGrpcService service.
// All implementations must embed UnimplementedSeGrpcServiceServer
// for forward compatibility
type SeGrpcServiceServer interface {
	GetCustomers(context.Context, *GetCustomersReq) (*Customers, error)
	GetCustomerById(context.Context, *GetCustomersReq) (*Customer, error)
	CreateCustomer(context.Context, *Customer) (*wrapperspb.BoolValue, error)
	UpdateCustomer(context.Context, *UpdateCustomerReq) (*wrapperspb.BoolValue, error)
	mustEmbedUnimplementedSeGrpcServiceServer()
}

// UnimplementedSeGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeGrpcServiceServer struct {
}

func (UnimplementedSeGrpcServiceServer) GetCustomers(context.Context, *GetCustomersReq) (*Customers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomers not implemented")
}
func (UnimplementedSeGrpcServiceServer) GetCustomerById(context.Context, *GetCustomersReq) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerById not implemented")
}
func (UnimplementedSeGrpcServiceServer) CreateCustomer(context.Context, *Customer) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedSeGrpcServiceServer) UpdateCustomer(context.Context, *UpdateCustomerReq) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomer not implemented")
}
func (UnimplementedSeGrpcServiceServer) mustEmbedUnimplementedSeGrpcServiceServer() {}

// UnsafeSeGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeGrpcServiceServer will
// result in compilation errors.
type UnsafeSeGrpcServiceServer interface {
	mustEmbedUnimplementedSeGrpcServiceServer()
}

func RegisterSeGrpcServiceServer(s grpc.ServiceRegistrar, srv SeGrpcServiceServer) {
	s.RegisterService(&SeGrpcService_ServiceDesc, srv)
}

func _SeGrpcService_GetCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeGrpcServiceServer).GetCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.SeGrpcService/GetCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeGrpcServiceServer).GetCustomers(ctx, req.(*GetCustomersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeGrpcService_GetCustomerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeGrpcServiceServer).GetCustomerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.SeGrpcService/GetCustomerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeGrpcServiceServer).GetCustomerById(ctx, req.(*GetCustomersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeGrpcService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeGrpcServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.SeGrpcService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeGrpcServiceServer).CreateCustomer(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeGrpcService_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeGrpcServiceServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.SeGrpcService/UpdateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeGrpcServiceServer).UpdateCustomer(ctx, req.(*UpdateCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SeGrpcService_ServiceDesc is the grpc.ServiceDesc for SeGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.SeGrpcService",
	HandlerType: (*SeGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomers",
			Handler:    _SeGrpcService_GetCustomers_Handler,
		},
		{
			MethodName: "GetCustomerById",
			Handler:    _SeGrpcService_GetCustomerById_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _SeGrpcService_CreateCustomer_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _SeGrpcService_UpdateCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
