// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.secommerce.customer.grpc;

public final class CustomerGrpc {
  private CustomerGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * model
   * </pre>
   *
   * Protobuf enum {@code customer.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.secommerce.customer.grpc.CustomerGrpc.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:customer.Gender)
  }

  public interface CustomersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:customer.Customers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    java.util.List<com.secommerce.customer.grpc.CustomerGrpc.Customer> 
        getCustomersList();
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    com.secommerce.customer.grpc.CustomerGrpc.Customer getCustomers(int index);
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    int getCustomersCount();
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    java.util.List<? extends com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder> 
        getCustomersOrBuilderList();
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder getCustomersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code customer.Customers}
   */
  public  static final class Customers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:customer.Customers)
      CustomersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customers.newBuilder() to construct.
    private Customers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customers() {
      customers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                customers_ = new java.util.ArrayList<com.secommerce.customer.grpc.CustomerGrpc.Customer>();
                mutable_bitField0_ |= 0x00000001;
              }
              customers_.add(
                  input.readMessage(com.secommerce.customer.grpc.CustomerGrpc.Customer.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          customers_ = java.util.Collections.unmodifiableList(customers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secommerce.customer.grpc.CustomerGrpc.Customers.class, com.secommerce.customer.grpc.CustomerGrpc.Customers.Builder.class);
    }

    public static final int CUSTOMERS_FIELD_NUMBER = 1;
    private java.util.List<com.secommerce.customer.grpc.CustomerGrpc.Customer> customers_;
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    public java.util.List<com.secommerce.customer.grpc.CustomerGrpc.Customer> getCustomersList() {
      return customers_;
    }
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    public java.util.List<? extends com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder> 
        getCustomersOrBuilderList() {
      return customers_;
    }
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    public int getCustomersCount() {
      return customers_.size();
    }
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    public com.secommerce.customer.grpc.CustomerGrpc.Customer getCustomers(int index) {
      return customers_.get(index);
    }
    /**
     * <code>repeated .customer.Customer customers = 1;</code>
     */
    public com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder getCustomersOrBuilder(
        int index) {
      return customers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customers_.size(); i++) {
        output.writeMessage(1, customers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.secommerce.customer.grpc.CustomerGrpc.Customers)) {
        return super.equals(obj);
      }
      com.secommerce.customer.grpc.CustomerGrpc.Customers other = (com.secommerce.customer.grpc.CustomerGrpc.Customers) obj;

      if (!getCustomersList()
          .equals(other.getCustomersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomersCount() > 0) {
        hash = (37 * hash) + CUSTOMERS_FIELD_NUMBER;
        hash = (53 * hash) + getCustomersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.secommerce.customer.grpc.CustomerGrpc.Customers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code customer.Customers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:customer.Customers)
        com.secommerce.customer.grpc.CustomerGrpc.CustomersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.secommerce.customer.grpc.CustomerGrpc.Customers.class, com.secommerce.customer.grpc.CustomerGrpc.Customers.Builder.class);
      }

      // Construct using com.secommerce.customer.grpc.CustomerGrpc.Customers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCustomersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (customersBuilder_ == null) {
          customers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          customersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customers_descriptor;
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.Customers getDefaultInstanceForType() {
        return com.secommerce.customer.grpc.CustomerGrpc.Customers.getDefaultInstance();
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.Customers build() {
        com.secommerce.customer.grpc.CustomerGrpc.Customers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.Customers buildPartial() {
        com.secommerce.customer.grpc.CustomerGrpc.Customers result = new com.secommerce.customer.grpc.CustomerGrpc.Customers(this);
        int from_bitField0_ = bitField0_;
        if (customersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            customers_ = java.util.Collections.unmodifiableList(customers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customers_ = customers_;
        } else {
          result.customers_ = customersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.secommerce.customer.grpc.CustomerGrpc.Customers) {
          return mergeFrom((com.secommerce.customer.grpc.CustomerGrpc.Customers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.secommerce.customer.grpc.CustomerGrpc.Customers other) {
        if (other == com.secommerce.customer.grpc.CustomerGrpc.Customers.getDefaultInstance()) return this;
        if (customersBuilder_ == null) {
          if (!other.customers_.isEmpty()) {
            if (customers_.isEmpty()) {
              customers_ = other.customers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomersIsMutable();
              customers_.addAll(other.customers_);
            }
            onChanged();
          }
        } else {
          if (!other.customers_.isEmpty()) {
            if (customersBuilder_.isEmpty()) {
              customersBuilder_.dispose();
              customersBuilder_ = null;
              customers_ = other.customers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomersFieldBuilder() : null;
            } else {
              customersBuilder_.addAllMessages(other.customers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.secommerce.customer.grpc.CustomerGrpc.Customers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.secommerce.customer.grpc.CustomerGrpc.Customers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.secommerce.customer.grpc.CustomerGrpc.Customer> customers_ =
        java.util.Collections.emptyList();
      private void ensureCustomersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          customers_ = new java.util.ArrayList<com.secommerce.customer.grpc.CustomerGrpc.Customer>(customers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.secommerce.customer.grpc.CustomerGrpc.Customer, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder, com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder> customersBuilder_;

      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public java.util.List<com.secommerce.customer.grpc.CustomerGrpc.Customer> getCustomersList() {
        if (customersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customers_);
        } else {
          return customersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public int getCustomersCount() {
        if (customersBuilder_ == null) {
          return customers_.size();
        } else {
          return customersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public com.secommerce.customer.grpc.CustomerGrpc.Customer getCustomers(int index) {
        if (customersBuilder_ == null) {
          return customers_.get(index);
        } else {
          return customersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder setCustomers(
          int index, com.secommerce.customer.grpc.CustomerGrpc.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.set(index, value);
          onChanged();
        } else {
          customersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder setCustomers(
          int index, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.set(index, builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder addCustomers(com.secommerce.customer.grpc.CustomerGrpc.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.add(value);
          onChanged();
        } else {
          customersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder addCustomers(
          int index, com.secommerce.customer.grpc.CustomerGrpc.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.add(index, value);
          onChanged();
        } else {
          customersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder addCustomers(
          com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.add(builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder addCustomers(
          int index, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.add(index, builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder addAllCustomers(
          java.lang.Iterable<? extends com.secommerce.customer.grpc.CustomerGrpc.Customer> values) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customers_);
          onChanged();
        } else {
          customersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder clearCustomers() {
        if (customersBuilder_ == null) {
          customers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public Builder removeCustomers(int index) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.remove(index);
          onChanged();
        } else {
          customersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder getCustomersBuilder(
          int index) {
        return getCustomersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder getCustomersOrBuilder(
          int index) {
        if (customersBuilder_ == null) {
          return customers_.get(index);  } else {
          return customersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public java.util.List<? extends com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder> 
           getCustomersOrBuilderList() {
        if (customersBuilder_ != null) {
          return customersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customers_);
        }
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder addCustomersBuilder() {
        return getCustomersFieldBuilder().addBuilder(
            com.secommerce.customer.grpc.CustomerGrpc.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder addCustomersBuilder(
          int index) {
        return getCustomersFieldBuilder().addBuilder(
            index, com.secommerce.customer.grpc.CustomerGrpc.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .customer.Customer customers = 1;</code>
       */
      public java.util.List<com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder> 
           getCustomersBuilderList() {
        return getCustomersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.secommerce.customer.grpc.CustomerGrpc.Customer, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder, com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder> 
          getCustomersFieldBuilder() {
        if (customersBuilder_ == null) {
          customersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.secommerce.customer.grpc.CustomerGrpc.Customer, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder, com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder>(
                  customers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          customers_ = null;
        }
        return customersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:customer.Customers)
    }

    // @@protoc_insertion_point(class_scope:customer.Customers)
    private static final com.secommerce.customer.grpc.CustomerGrpc.Customers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.secommerce.customer.grpc.CustomerGrpc.Customers();
    }

    public static com.secommerce.customer.grpc.CustomerGrpc.Customers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customers>
        PARSER = new com.google.protobuf.AbstractParser<Customers>() {
      @java.lang.Override
      public Customers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.secommerce.customer.grpc.CustomerGrpc.Customers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:customer.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string first_name = 1;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string phone = 4;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 4;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>.customer.Gender gender = 5;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <code>.customer.Gender gender = 5;</code>
     * @return The gender.
     */
    com.secommerce.customer.grpc.CustomerGrpc.Gender getGender();
  }
  /**
   * Protobuf type {@code customer.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:customer.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      phone_ = "";
      gender_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secommerce.customer.grpc.CustomerGrpc.Customer.class, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder.class);
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 1;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 2;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 4;</code>
     * @return The phone.
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 4;</code>
     * @return The bytes for phone.
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 5;
    private int gender_;
    /**
     * <code>.customer.Gender gender = 5;</code>
     * @return The enum numeric value on the wire for gender.
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.customer.Gender gender = 5;</code>
     * @return The gender.
     */
    public com.secommerce.customer.grpc.CustomerGrpc.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.secommerce.customer.grpc.CustomerGrpc.Gender result = com.secommerce.customer.grpc.CustomerGrpc.Gender.valueOf(gender_);
      return result == null ? com.secommerce.customer.grpc.CustomerGrpc.Gender.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phone_);
      }
      if (gender_ != com.secommerce.customer.grpc.CustomerGrpc.Gender.MALE.getNumber()) {
        output.writeEnum(5, gender_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phone_);
      }
      if (gender_ != com.secommerce.customer.grpc.CustomerGrpc.Gender.MALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, gender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.secommerce.customer.grpc.CustomerGrpc.Customer)) {
        return super.equals(obj);
      }
      com.secommerce.customer.grpc.CustomerGrpc.Customer other = (com.secommerce.customer.grpc.CustomerGrpc.Customer) obj;

      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (gender_ != other.gender_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.secommerce.customer.grpc.CustomerGrpc.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code customer.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:customer.Customer)
        com.secommerce.customer.grpc.CustomerGrpc.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.secommerce.customer.grpc.CustomerGrpc.Customer.class, com.secommerce.customer.grpc.CustomerGrpc.Customer.Builder.class);
      }

      // Construct using com.secommerce.customer.grpc.CustomerGrpc.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        email_ = "";

        phone_ = "";

        gender_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_Customer_descriptor;
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.Customer getDefaultInstanceForType() {
        return com.secommerce.customer.grpc.CustomerGrpc.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.Customer build() {
        com.secommerce.customer.grpc.CustomerGrpc.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.Customer buildPartial() {
        com.secommerce.customer.grpc.CustomerGrpc.Customer result = new com.secommerce.customer.grpc.CustomerGrpc.Customer(this);
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.email_ = email_;
        result.phone_ = phone_;
        result.gender_ = gender_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.secommerce.customer.grpc.CustomerGrpc.Customer) {
          return mergeFrom((com.secommerce.customer.grpc.CustomerGrpc.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.secommerce.customer.grpc.CustomerGrpc.Customer other) {
        if (other == com.secommerce.customer.grpc.CustomerGrpc.Customer.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.secommerce.customer.grpc.CustomerGrpc.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.secommerce.customer.grpc.CustomerGrpc.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 1;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 1;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 1;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 1;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 4;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 4;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 4;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 4;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.customer.Gender gender = 5;</code>
       * @return The enum numeric value on the wire for gender.
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.customer.Gender gender = 5;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.customer.Gender gender = 5;</code>
       * @return The gender.
       */
      public com.secommerce.customer.grpc.CustomerGrpc.Gender getGender() {
        @SuppressWarnings("deprecation")
        com.secommerce.customer.grpc.CustomerGrpc.Gender result = com.secommerce.customer.grpc.CustomerGrpc.Gender.valueOf(gender_);
        return result == null ? com.secommerce.customer.grpc.CustomerGrpc.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>.customer.Gender gender = 5;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(com.secommerce.customer.grpc.CustomerGrpc.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.customer.Gender gender = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:customer.Customer)
    }

    // @@protoc_insertion_point(class_scope:customer.Customer)
    private static final com.secommerce.customer.grpc.CustomerGrpc.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.secommerce.customer.grpc.CustomerGrpc.Customer();
    }

    public static com.secommerce.customer.grpc.CustomerGrpc.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.secommerce.customer.grpc.CustomerGrpc.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetAllCustomersReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:customer.GetAllCustomersReq)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * request
   * </pre>
   *
   * Protobuf type {@code customer.GetAllCustomersReq}
   */
  public  static final class GetAllCustomersReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:customer.GetAllCustomersReq)
      GetAllCustomersReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetAllCustomersReq.newBuilder() to construct.
    private GetAllCustomersReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAllCustomersReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetAllCustomersReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetAllCustomersReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_GetAllCustomersReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_GetAllCustomersReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.class, com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq)) {
        return super.equals(obj);
      }
      com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq other = (com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * request
     * </pre>
     *
     * Protobuf type {@code customer.GetAllCustomersReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:customer.GetAllCustomersReq)
        com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_GetAllCustomersReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_GetAllCustomersReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.class, com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.Builder.class);
      }

      // Construct using com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.secommerce.customer.grpc.CustomerGrpc.internal_static_customer_GetAllCustomersReq_descriptor;
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq getDefaultInstanceForType() {
        return com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq build() {
        com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq buildPartial() {
        com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq result = new com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq) {
          return mergeFrom((com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq other) {
        if (other == com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:customer.GetAllCustomersReq)
    }

    // @@protoc_insertion_point(class_scope:customer.GetAllCustomersReq)
    private static final com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq();
    }

    public static com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAllCustomersReq>
        PARSER = new com.google.protobuf.AbstractParser<GetAllCustomersReq>() {
      @java.lang.Override
      public GetAllCustomersReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAllCustomersReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAllCustomersReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAllCustomersReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.secommerce.customer.grpc.CustomerGrpc.GetAllCustomersReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_Customers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_Customers_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_GetAllCustomersReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_GetAllCustomersReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\010customer\"2\n\tCustomers\022" +
      "%\n\tcustomers\030\001 \003(\0132\022.customer.Customer\"q" +
      "\n\010Customer\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlast_n" +
      "ame\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\r\n\005phone\030\004 \001(\t\022" +
      " \n\006gender\030\005 \001(\0162\020.customer.Gender\"\024\n\022Get" +
      "AllCustomersReq*\036\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006F" +
      "EMALE\020\0012W\n\rSeGrpcService\022F\n\017GetAllCustom" +
      "ers\022\034.customer.GetAllCustomersReq\032\023.cust" +
      "omer.Customers\"\000B,\n\034com.secommerce.custo" +
      "mer.grpcB\014CustomerGrpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_customer_Customers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_customer_Customers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_Customers_descriptor,
        new java.lang.String[] { "Customers", });
    internal_static_customer_Customer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_customer_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_Customer_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Phone", "Gender", });
    internal_static_customer_GetAllCustomersReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_customer_GetAllCustomersReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_GetAllCustomersReq_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
